## Simple Linear Regression

### Problem Statement: Build a Linear Regression model that predicts the profit of startupts on basis of Administration charges

In [15]:
import pandas as pd
path = r"E:\Sindhura\DataSets\50_Startups.csv"
df = pd.read_csv('50_Startups.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '50_Startups.csv'

## Perform basic data quality checks

In [ ]:
df.shape

(50, 5)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RND     50 non-null     float64
 1   ADMIN   50 non-null     float64
 2   MKT     50 non-null     float64
 3   STATE   50 non-null     str
 4   PROFIT  50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 2.1 KB

## Separate X and Y features

In [ ]:
X = df[['ADMIN']]
Y = df[['PROFIT']]

NameError: name 'df' is not defined

In [ ]:
X.head()

       ADMIN
0  136897.80
1  151377.59
2  101145.55
3  118671.85
4   91391.77

In [ ]:
Y.head()

      PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

## Ypredictions = B0 + B1.ADMIN

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [ ]:
X.head()

       ADMIN
0  136897.80
1  151377.59
2  101145.55
3  118671.85
4   91391.77

In [ ]:
# B0 -> Intercept
model.intercept_

array([76974.47130542])

In [ ]:
# Coefficient -> Slope -> B1
model.coef_

array([[0.2887492]])

## PROFIT_Predictions = B0+B1.ADMIN
PROFIT_Predictions = 76974.47 + (0.288 * ADMIN )

  IF the ADMIN = 0, PROFIT_Predictions will be 76974
  profits increase by 0.288 times ADMIN charges

In [ ]:
model.score(X,Y)

0.04028714077757223

## Performance Metrics
    MSE, RMSE
    MAE
    R2

In [ ]:
Ypreds = model.predict(X)
Ypreds

array([[116503.6018596 ],
       [120684.62967237],
       [106180.1681897 ],
       [111240.87333494],
       [103363.77199475],
       [105795.88920124],
       [119478.02760551],
       [118996.16004913],
       [119916.94949302],
       [108355.49495555],
       [108908.4323531 ],
       [103478.93672662],
       [113738.12947398],
       [116098.56469098],
       [122177.41396119],
       [112379.98605074],
       [112085.66687627],
       [118865.50681004],
       [109942.6395962 ],
       [121301.54811819],
       [109853.56335476],
       [121376.42656134],
       [112427.8924309 ],
       [107509.99686616],
       [105641.87903918],
       [117270.33494157],
       [118593.62056111],
       [113895.25812743],
       [129713.23106914],
       [121162.35656519],
       [110365.79866475],
       [121067.02890353],
       [114286.53062157],
       [106732.23933965],
       [122508.46492169],
       [101531.85176777],
       [113661.8505972 ],
       [ 91782.43707469],
       [ 96016.8834899 ],
       [100935.48360269],
       [111204.54868528],
       [101434.63857381],
       [104749.15024276],
       [113756.00882459],
       [121674.62075011],
       [112823.56257539],
       [110416.30956272],
       [116078.88643284],
       [ 91915.26459526],
       [110753.4502439 ]])

In [ ]:
Ypreds[:5]

array([[116503.6018596 ],
       [120684.62967237],
       [106180.1681897 ],
       [111240.87333494],
       [103363.77199475]])

In [ ]:
Y.head()

      PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mse = mean_squared_error(Y,Ypreds)
mae = mean_absolute_error(Y,Ypreds)
rmse = mse**(1/2)
r2 = r2_score(Y,Ypreds)

print(f"MSE:{mse}")
print(f"RMSE:{rmse}")
print(f"MAE:{mae}")
print(f"Rsquared:{r2*100}%")

MSE:1527955397.744143
RMSE:39089.07005473708
MAE:30659.814789071817
Rsquared:4.028714077757223%

## R squared is close to 0. This model is resulting in inaccurate results. We will not consider this model as our final model

## -------------------------------------------------------------------------------
## Build the model that predicts PROFIT for the startups by considering RND amount
X1 = df[['RND']]